services:
  api:
    container_name: user_api
    build:
      context: build_docker
      dockerfile: Dockerfile
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8000:8000'      
    volumes:
      - ./api:/app
      - ./classes:/app/classes
      - user_data:/data

  test:
    container_name: user_test
    build:
      context: build_docker
      dockerfile: Dockerfile.test
    volumes:
      - ./test:/app
      - ./classes:/app/classes
      - user_data:/data
    environment:
      - PYTHONUNBUFFERED=1

volumes:
    user_data: