FROM python:latest

WORKDIR /app

COPY requirements_test.txt .
RUN pip install --no-cache-dir -r requirements_test.txt

#COPY test/test.py .

#CMD ["python", "main.py"]
CMD ["tail", "-f", "/dev/null"]